#ifndef _BOARD_TYPE_H_
#define _BOARD_TYPE_H_

typedef enum {
    BOARD_TYPE_UNKNOWN,

    BOARD_TYPE_RPI_ZERO,
    BOARD_TYPE_RPI_ZERO_W,
    BOARD_TYPE_RPI_1_A,
    BOARD_TYPE_RPI_1_A_PLUS,
    BOARD_TYPE_RPI_1_B,
    BOARD_TYPE_RPI_1_B_PLUS,
    BOARD_TYPE_RPI_2_B,
    BOARD_TYPE_RPI_3_B,

    BOARD_TYPE_ARDUINO_UNO,
    BOARD_TYPE_ARDUINO_DUEMILANOVE,
    BOARD_TYPE_ARDUINO_DIECIMILA,
    BOARD_TYPE_ARDUINO_EXTREME,
    BOARD_TYPE_ARDUINO_EXTREME_V2,
    BOARD_TYPE_ARDUINO_NG_240,
    BOARD_TYPE_ARDUINO_NG_REV_C,
    BOARD_TYPE_ARDUINO_USB,
    BOARD_TYPE_ARDUINO_USB_V2,
    BOARD_TYPE_ARDUINO_BT,
    BOARD_TYPE_ARDUINO_SERIAL,
    BOARD_TYPE_ARDUINO_SERIAL_V2,
    BOARD_TYPE_ARDUINO_SEVERINO,
    BOARD_TYPE_ARDUINO_MEGA,
    BOARD_TYPE_ARDUINO_LILYPAD_0,
    BOARD_TYPE_ARDUINO_LILYPAD_1,
    BOARD_TYPE_ARDUINO_LILYPAD_2,
    BOARD_TYPE_ARDUINO_LILYPAD_3,
    BOARD_TYPE_ARDUINO_LILYPAD_4,
    BOARD_TYPE_ARDUINO_NANO_2,
    BOARD_TYPE_ARDUINO_NANO_3,
    BOARD_TYPE_ARDUINO_MINI_3,
    BOARD_TYPE_ARDUINO_MINI_4,
    BOARD_TYPE_ARDUINO_STAMP_2,
    BOARD_TYPE_ARDUINO_MINI_USB_ADAPTER_3,
    BOARD_TYPE_ARDUINO_ROBOT,

    BOARD_TYPE_ARDUINO_YUN_W_POE,               // A000003
    BOARD_TYPE_ARDUINO_USB_HOST_SHIELD,         // A000004
    BOARD_TYPE_ARDUINO_NANO,                    // A000005
    BOARD_TYPE_ARDUINO_YUN,                     // A000008
    BOARD_TYPE_ARDUINO_LILYPAD_MAIN,            // A000011
    BOARD_TYPE_ARDUINO_USB_SERIAL_CONVERTER,    // A000014
    BOARD_TYPE_ARDUINO_MINI_USB_ADAPTER,        // A000015
    BOARD_TYPE_ARDUINO_LEONARDO_ETH,            // A000022
    BOARD_TYPE_ARDUINO_LEONARDO_ETH_2_W_POE,    // A000023
    BOARD_TYPE_ARDUINO_ETHERNET_SHIELD_2,       // A000024
    BOARD_TYPE_ARDUINO_ETHERNET_SHIELD_2_W_POE, // A000025
    BOARD_TYPE_ARDUINO_GSM_SHIELD,              // A000043
    BOARD_TYPE_ARDUINO_MICRO,                   // A000053
    BOARD_TYPE_ARDUINO_DUE_WO_HEADERS,          // A000056
    BOARD_TYPE_ARDUINO_LEONARDO_W_HEADERS,      // A000057
    BOARD_TYPE_ARDUINO_WIFI_SHIELD,             // A000058
    BOARD_TYPE_ARDUINO_DUE,                     // A000062
    BOARD_TYPE_ARDUINO_MEGA_2560_REV3,          // A000067
    BOARD_TYPE_ARDUINO_ETHERNET_REV3_WO_POE,    // A000068
    BOARD_TYPE_ARDUINO_MEGA_ADK_REV3,           // A000069
    BOARD_TYPE_ARDUINO_ETHERNET_SHIELD_WO_POE,  // A000072
    BOARD_TYPE_ARDUINO_UNO_REV3_SMD,            // A000073
    BOARD_TYPE_ARDUINO_ETHERNET_REV3_W_POE,     // A000074
    BOARD_TYPE_ARDUINO_MOTOR_SHIELD_REV3,       // A000079
    BOARD_TYPE_ARDUINO_MEGA_PROTO_SHIELD,       // A000080
    BOARD_TYPE_ARDUINO_MINI_5,                  // A000087
    BOARD_TYPE_ARDUINO_ISP,                     // A000092
    BOARD_TYPE_ARDUINO_MICRO_WO_HEADERS,        // A000093
    BOARD_TYPE_ARDUINO_LCD_SCREEN,              // A000096
    BOARD_TYPE_ARDUINO_UNO_REV3_LONG_PINS,      // A000099
    BOARD_TYPE_ARDUINO_M0,                      // A000103
    BOARD_TYPE_ARDUINO_GSM_SHIELD_2_INT_ANT,    // A000105
    BOARD_TYPE_ARDUINO_USB_2_SERIAL,            // A000107
    BOARD_TYPE_ARDUINO_YUN_MINI,                // A000108
    BOARD_TYPE_ARDUINO_4_RELAYS_SHIELD,         // A000110
    BOARD_TYPE_ARDUINO_TIAN,                    // A000116
    BOARD_TYPE_ARDUINO_LUCKY_SHIELD,            // A000125
    BOARD_TYPE_ARDUINO_UNO_WIFI,                // A000133
    BOARD_TYPE_ARDUINO_PRIMO,                   // A000135
    BOARD_TYPE_ARDUINO_PRIMO_CORE,              // A000138
    BOARD_TYPE_ARDUINO_GEMMA,                   // ABX00001
    BOARD_TYPE_ARDUINO_MKR1000_WIFI,            // ABX00004
    BOARD_TYPE_ARDUINO_MKR1000_WIFI_W_HEADERS,  // ABX00011
    BOARD_TYPE_ARDUINO_MKR_ZERO,                // ABX00012
    BOARD_TYPE_ARDUINO_MKR_FOX_1200,            // ABX00014-B
    BOARD_TYPE_ARDUINO_MKR_WAN_1300,            // ABX00017-B
    BOARD_TYPE_ARDUINO_MKR_GSM_1400,            // ABX00018-B
    BOARD_TYPE_ARDUINO_EARTHLCD,                // AH00005
    BOARD_TYPE_ARDUINO_AH_BLEND_MICRO,          // AH00007
    BOARD_TYPE_ARDUINO_4DUINO_TOUCHSCREEN,      // AH00008
    BOARD_TYPE_ARDUINO_INDUSTRUINO_PROTO_D21G,  // AH00010
    BOARD_TYPE_ARDUINO_WIFI_101_SHIELD,         // ASX00001
    BOARD_TYPE_ARDUINO_LILYPAD_USB,             // E000017
    BOARD_TYPE_ARDUINO_PRO,                     // E000023 (SparkFun)
    BOARD_TYPE_ARDUINO_PRO_MINI,                // E000025 (SparkFun)
    BOARD_TYPE_ARDUINO_LILYPAD_XBEE,            // E000027
    BOARD_TYPE_ARDUINO_FIO,                     // E000055
    BOARD_TYPE_ARDUINO_LILYPAD_SIMPLESNAP,      // E000059
    BOARD_TYPE_ARDUINO_INDUSTRUINO_ETHERNET_EX, // E000095
    BOARD_TYPE_GENUINO_ZERO,                    // GBX00003
    BORAD_TYPE_GENUINO_101,                     // GBX00005
    BOARD_TYPE_GENUINO_UNO_REV3,                // GBX00066
    BOARD_TYPE_ARDUINO_MKR_PROTO_SHIELD,        // TSX00001
    BOARD_TYPE_ARDUINO_MKR_PROTO_LARGE_SHIELD,  // TSX00002
    BOARD_TYPE_ARDUINO_MKR_RELAY_PROTO_SHIELD,  // TSX00003
    BOARD_TYPE_ARDUINO_MKR2UNO_ADAPTER,         // TSX00005
    BOARD_TYPE_ARDUINO_EDUCATION_SHIELD,        // TSX00006
    BOARD_TYPE_ARDUINO_PROTO_SHIELD_REV3_UNO    // TSX00083
} BoardType;

#endif /* _BOARD_TYPE_H_ */
